// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ymqlxuqdbilpffwbvtth.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InltcWx4dXFkYmlscGZmd2J2dHRoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ1OTQ5NjgsImV4cCI6MjA2MDE3MDk2OH0.OBk6DBkvGX8usQqERkrCG_Zn0TMISnsQSy5_QSpMMqg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);